### ISSUE TITLE
Suggestion: ability to plot lines

### ISSUE THREAD

**Issue by davnovak** [exaexa/scattermore#1]
Thanks a lot, _scattermore_ is splendid!

Here is a suggestion, straight out of my wish list: I would appreciate the ability to plot lines using _scattermore_. This is not possible now. I include a chunk of code showing the base graphics approach which would be mimicked.
```
a      <- c(2, 3)
b      <- c(5, 7)
coords <- rbind(a, b)

## base graphics
plot(coords, xlim = c(0, 10), ylim = c(0, 10), type = 'l')
```
---
**Temporary solution**

Now, if anybody else stumbles upon this problem, it can be circumvented by doing something like this:
```
## scattermore with interpolation
N      <- 500
dots   <- apply(coords, 2, function(x) seq(x[1], x[2], length.out = N))
scattermore::scattermoreplot(dots, xlim = c(0, 10), ylim = c(0, 10))

```
Or, if we're dealing with a lot of lines and the interpolation step would require using a lot of for-loops, computing the coordinates of each dot can be done via Rcpp. This is how I currently solve the problem.

Cheers

**Comment by exaexa** [comment]
I don't want to implement the linepainting for various widths of lines (b/c that already sucks a lot in the code); I'm instead going to try the gigascatter way (kernelizing the pixels to make them look bigger, which should work nicely on lines as well). It's also going to be much faster for plotting lots of big points.

**Comment by exaexa** [comment]
Putting this here to motivate myself further:
https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm

**Comment by exaexa** [comment]
Some update: there's ongoing work on scattermore "version 2" now, merging some extra ideas from GigaScatter. Lines (and likely some other extra shapes) will be supported.

**Comment by brunomioto** [comment]
+1 !!
