### ISSUE TITLE
alpha(coords$colour, coords$alpha) not found

### ISSUE THREAD

**Issue by roman-tremmel** [exaexa/scattermore#4]
I want to use your function scattermore::geom_scattermore()  in my function build into a new R package. After a clean install, I recieve following error:

    Fehler in alpha(coords$colour, coords$alpha) : 
        konnte Funktion "alpha" nicht finden 

Which means that the ggplot2::alpha function is not found. After loading ggplot2 library, the error is gone. But I don't like to load ggplot in my package using library or require. Can you fix that for instance in line 209?

**Comment by exaexa** [comment]
Hello! Thank you for reporting, it seems like I forgot to prefix the function with package prefix so that it works even without explicit library import.

Can you try with the latest commit from git master? (eg. `devtools::install_github('exaexa/scattermore', dependencies=F)`)

**Comment by roman-tremmel** [comment]
perfect. Works now as expected.

**Comment by roman-tremmel** [comment]
perfect. Works now as expected.

**Comment by exaexa** [comment]
Great, thanks again! Can you (for now) use the version from git, or should I try to push a fixed release to CRAN asap?

**Comment by roman-tremmel** [comment]
I will use the git version. Since my package is more an internal one it's ok for now. Thanks for the fast response and the nice package.
